### ISSUE TITLE
Add interests of related people to link title

### ISSUE THREAD

**Issue by marpa** [clas-web/related-people#1]
Add interests of related people to link title so that when users hover over related people links they will see all the interests of that related person

**Comment by marpa** [comment]
almost done, see: 3c854335991f114b7b7393c14389bac6d95fd5aa

**Comment by marpa** [comment]
Modify css for related person interests aria box so it is styled like interest tags (i.e. yellow background):
    box-shadow: 0px 0px 3px #222222;
    background-color: #FFF6DC;
    color: #696969;

**Comment by rmccal14** [comment]
@marpa done: https://github.com/clas-web/unc-charlotte-theme/commit/caf0780eb3f5922b852ee6d57f81a903805310c6

https://devpages.uncc.edu/connections/people/jyavorsk/

![image](https://user-images.githubusercontent.com/41296669/67499875-c46f7980-f64f-11e9-8c8c-228bc1951430.png)

**Comment by marpa** [comment]
Let's do the same for number of related people aria box (i.e. style it like related people links:
![image](https://user-images.githubusercontent.com/134851/67503582-dc49fc00-f655-11e9-8d5d-52a3c286164a.png)

#content .connection-links a[aria-label]:after {
    background-color: #fff;
    padding: 2px 5px;
}

**Comment by marpa** [comment]
Let's lose the space between groups and academic interests:
content: attr(aria-label) '' attr(data-title);

**Comment by rmccal14** [comment]
@marpa Done, I like this idea!

Academic Interests mouseover now matches Related People: 
![image](https://user-images.githubusercontent.com/41296669/67513418-c3971180-f668-11e9-8901-167873953370.png)

And Related People now match Academic Interests (minus the line break):
![image](https://user-images.githubusercontent.com/41296669/67513429-cb56b600-f668-11e9-8253-6d4030dbf25a.png)

https://devpages.uncc.edu/connections/people/jyavorsk/

**Comment by marpa** [comment]
The padding for the academic interests mouseover seems a bit too much.... 
`padding: .5em .5em .5em .5em;`

Can you make it the same as related people links:
`padding: 2px 5px;`

**Comment by rmccal14** [comment]
Done:  clas-web/unc-charlotte-theme@0a97229

**Comment by rmccal14** [comment]
Completed: #2
